### ISSUE TITLE
Reword texts?

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#34]
Ist it possible to rename texts "easily"? Are there central locale files or something like that where we can change German wordings?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
Yes, we can rename texts easily by overwritting the texts in protected/config/messages. 

**For example convert text into german language**

1. First create a language code folder in message directory. 'de' is the language code for german language
2.  Create a file in language code folder and name of file should be (ModuleId.MessageFile.php) like SpaceModule.base.php
3. Rename or overwrite the text you want in the file.

MessageFile = it is a file present in moduleName/messages/languagecode/base.php. in this file all translation of different language is present

![image](https://user-images.githubusercontent.com/103625795/176448564-843a8172-edd0-40d2-b6c6-3e5645e92521.png)

**Example**  

To overwrite the text of space in the German language, for example, you have to create the following file:

- config/messages/de/SpaceModule.base.php

with content
![image](https://user-images.githubusercontent.com/103625795/176449031-81add6e0-96c4-42ed-b03e-99b87e9e01fe.png)

You can give us a list of texts that you want to rename so that we can rename those texts
Thanks!

**Comment by donni106** [comment]
Thanks, your explanation was very helpful. We need to find an internal solution as it is too hard to tell which texts to change where.
