### ISSUE TITLE
Add endpoint to mark unread conversations as read

### ISSUE THREAD

**Issue by donni106** [ikuseiGmbH/smart-village-app-humhub-ext#5]
After implementation of #4 we know which conversations have new messages. With opening such conversations we need the ability to mark them as read. Therefore we need a new PUT endpoint `/mail/{id}/read` that changes the unread status to read. Maybe it is not needed to implement a new endpoint. With fetching `/mail/{id}/entries` the status can be set to read automatically. What do you think?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
If your interface is similar to Humhub then you need to separate endpoint. because in Humhub there are two steps to mark any conversation as read.
 1. open the all conversations by clicking on message icon.
 ![image](https://user-images.githubusercontent.com/103625795/166409679-8b8a81d4-7cf6-44ce-929f-c600640066d0.png)

 2. When you click on that conversation, only then it mark as read.
![image](https://user-images.githubusercontent.com/103625795/166409772-896bb827-2f8e-4abc-8265-d71076098196.png)

**Comment by donni106** [comment]
true! conversations should be marked as read in the time the conversation is opened/API gets called for conversation data.
but this is what i meant. the `/mail/{id}/entries` are already the conversation messages, like in your second screenshot. your first screenshot shows the data equal to the API endpoint `/mail`.

in addition to `/mail/{id}/entries` we could think about also marking as read when calling `/mail/{id}` and `/mail/{id}/entries/{id2}`, right?

**Comment by gaurav-handysolver** [comment]
Hi @donni106 
We Investigated this /mail/{id}/entries endpoint and we found that this endpoint is fetching all the messages of a particular conversation so, we can modified this endpoint's function so that when the user hit this API, all the unread messages of the conversation should be read.

What do you think about it?
Thanks!

**Comment by donni106** [comment]
Sounds good on first sight. But then i thought about the `/mail/{id}/entries` in detail. There can be two or more participants in a conversation. What if i send a message to you. After sending the message `/mail/{id}/entries` gets refetched over time to get new messages. In this case, i would directly mark the conversation read, right? I think we need to check, who is fetching the entries and who has send the last message, which is available per `updated_by: 5`.
This could work for 1:1 conversations.
But what if there are multiple persons writing in a group chat. Each of them need to have "their own" read status, right? So if person 1 is sending a messages, person 2 fetches `/mail/{id}/entries`, it can't be automatically read for person 3, right?

**Comment by donni106** [comment]
Ok the explanation in the other issue shows, that there can be differences on messages depending on users. As we request with a bearer token, the user is known. Thanks.

So with calling `/mail/{id}/entries` you will then update the `last_viewed` of the conversation for that user in the `user_message` table, right?
